#!/usr/bin/env Rscript

## ------------------------------------------------------------
## Step 6: Estimate hgRNA transition matrix P from two time points
##
## This script uses cell-level barcode outputs generated by the online
## LINEMAP preprocessing pipeline, or compatible saved cell-barcode files.
##
## Required inputs can be either current pipeline result directories:
##   <early_result>/cell_barcode/<target>/cell_level_barcode.rds
##   <late_result>/cell_barcode/<target>/cell_level_barcode.rds
##
## Or saved RDS/RData cell-barcode files:
##   --early_file d5/cell.read.d5.RData --early_object cell.read.d5A21
##   --late_file  d14/cell.read.d14.RData --late_object cell.read.d14A21
##
## Main outputs:
##   transition_node_<target>.tsv
##   transition_edges_<target>.tsv
##   P_transition_fsolve_<target>.tsv
##   P_transition_fsolve_<target>.rds
##   P_fsolve_fit_check_<target>.tsv
## ------------------------------------------------------------

parse_args <- function(args) {
  out <- list()
  i <- 1L
  while (i <= length(args)) {
    key <- sub("^--", "", args[[i]])
    if (i == length(args) || grepl("^--", args[[i + 1L]])) {
      out[[key]] <- TRUE
      i <- i + 1L
    } else {
      out[[key]] <- args[[i + 1L]]
      i <- i + 2L
    }
  }
  out
}

arg_or <- function(x, default) {
  if (is.null(x) || length(x) == 0L || is.na(x) || identical(x, "")) default else x
}

as_flag <- function(x, default = FALSE) {
  if (is.null(x)) return(default)
  tolower(as.character(x)) %in% c("1", "true", "t", "yes", "y")
}

matrix_power <- function(M, n) {
  if (n < 1L) stop("Matrix power must be >= 1.")
  ans <- M
  if (n == 1L) return(ans)
  for (i in 2L:n) ans <- ans %*% M
  ans
}

row_normalize <- function(M) {
  rs <- rowSums(M)
  rs[rs == 0] <- 1
  M / rs
}

write_matrix_tsv <- function(M, path) {
  write.table(M, file = path, quote = FALSE, sep = "\t",
              row.names = TRUE, col.names = NA)
}

choose_rdata_object <- function(object_names, target) {
  target_pat <- paste0(target, "$")
  preferred <- grep(paste0("^cell\\.read\\..*", target_pat), object_names, value = TRUE)
  if (length(preferred) > 0) return(preferred[[1]])

  preferred <- grep(paste0("^d[0-9]+", target_pat), object_names, value = TRUE)
  if (length(preferred) > 0) return(preferred[[1]])

  preferred <- grep(target_pat, object_names, value = TRUE)
  if (length(preferred) > 0) return(preferred[[1]])

  stop("Could not choose an object for target ", target,
       ". Available objects: ", paste(object_names, collapse = ", "))
}

load_cell_level_barcodes <- function(result_dir = NULL,
                                     file = NULL,
                                     object = NULL,
                                     target) {
  if (!is.null(file) && !is.na(file) && nzchar(file)) {
    if (!file.exists(file)) stop("Missing cell barcode file: ", file)

    if (grepl("\\.rds$", file, ignore.case = TRUE)) {
      x <- readRDS(file)
    } else if (grepl("\\.rdata$|\\.rda$", file, ignore.case = TRUE)) {
      env <- new.env(parent = emptyenv())
      object_names <- load(file, envir = env)
      if (is.null(object) || is.na(object) || !nzchar(object)) {
        object <- choose_rdata_object(object_names, target)
      }
      if (!object %in% object_names) {
        stop("Object ", object, " was not found in ", file,
             ". Available objects: ", paste(object_names, collapse = ", "))
      }
      x <- get(object, envir = env)
    } else {
      stop("Unsupported cell barcode file type: ", file)
    }

    if (!is.data.frame(x)) x <- as.data.frame(x, stringsAsFactors = FALSE)
    return(x)
  }

  path <- file.path(result_dir, "cell_barcode", target, "cell_level_barcode.rds")
  if (!file.exists(path)) stop("Missing pipeline output: ", path)

  x <- readRDS(path)
  if (!is.data.frame(x)) stop("Expected a data frame in: ", path)
  x
}

build_two_timepoint_node <- function(early_node,
                                     late_node,
                                     min_cells = 10L,
                                     selection = "min_cells",
                                     coverage = 0.90) {
  node <- merge(
    early_node[, c("read.short", "align.short", "mutation.report", "n")],
    late_node[, c("read.short", "align.short", "mutation.report", "n")],
    by = c("read.short", "align.short", "mutation.report"),
    all = TRUE,
    suffixes = c(".early", ".late")
  )

  if (nrow(node) == 0L) return(node)

  node$n.early[is.na(node$n.early)] <- 0L
  node$n.late[is.na(node$n.late)] <- 0L
  node$n <- node$n.early + node$n.late
  node <- node[order(node$n, decreasing = TRUE), , drop = FALSE]

  if (identical(selection, "min_cells")) {
    node <- node[node$n.early >= min_cells | node$n.late >= min_cells, , drop = FALSE]
  } else if (identical(selection, "coverage")) {
    if (sum(node$n) == 0) return(node[0, , drop = FALSE])
    idx <- which(cumsum(node$n) / sum(node$n) >= coverage)
    top_n <- if (length(idx) == 0L) nrow(node) else min(idx)
    node <- node[seq_len(top_n), , drop = FALSE]
  } else {
    stop("`selection` must be either 'min_cells' or 'coverage'.")
  }

  if (nrow(node) == 0L) return(node)

  root_row <- stringr::str_trim(node$mutation.report) == ""
  if (any(root_row)) {
    node <- node[order(!root_row, -node$n), , drop = FALSE]
  }

  node$node <- node$read.short
  node$node.symbol <- mutation_symbol_make(node$read.short, node$align.short)
  node$number.of.missing <- stringr::str_count(node$mutation.report, fixed("-"))
  node$p.early <- node$n.early / sum(node$n.early)
  node$p.late <- node$n.late / sum(node$n.late)

  ## Active mutations can continue evolving downstream; inactive mutations
  ## are treated as terminal/self-only states.
  node$active <- node$number.of.missing <= 5 & node$p.early > node$p.late
  node$active[stringr::str_trim(node$mutation.report) == "20-23 miss GGGG ----;"] <- FALSE
  node$category <- ifelse(node$active, 0L, 1L)

  node[, c("node", "node.symbol", "read.short", "align.short", "mutation.report",
           "n.early", "n.late", "n", "p.early", "p.late",
           "number.of.missing", "active", "category")]
}

collapse_for_transition <- function(cell_level_barcode,
                                    target,
                                    guide_rna,
                                    allele_mode = "auto") {
  if (identical(allele_mode, "auto")) {
    allele_mode <- if (identical(target, "A21") &&
                       all(c("mutation.correction1", "align.correction1",
                             "mutation.report") %in% colnames(cell_level_barcode))) {
      "legacy_hgrna_A21"
    } else {
      "standard"
    }
  }

  if (identical(allele_mode, "legacy_hgrna_A21")) {
    if (!identical(target, "A21")) {
      stop("allele_mode='legacy_hgrna_A21' is only defined for target A21.")
    }
    return(collapse_hgrna_A21_legacy_to_alleles(cell_level_barcode))
  }

  if (!identical(allele_mode, "standard")) {
    stop("Unknown allele_mode: ", allele_mode)
  }

  collapse_cell_barcode_to_alleles(cell_level_barcode, GuideRNA = guide_rna)
}

apply_state_annotation <- function(node, annotation_file = NULL) {
  if (is.null(annotation_file) || is.na(annotation_file) || !nzchar(annotation_file)) {
    return(node)
  }
  if (!file.exists(annotation_file)) stop("Missing state annotation file: ", annotation_file)

  anno <- read.delim(annotation_file, stringsAsFactors = FALSE, check.names = FALSE)
  if (!("mutation.report" %in% names(anno))) {
    stop("state annotation file must contain a 'mutation.report' column.")
  }
  if (!("active" %in% names(anno)) && !("category" %in% names(anno))) {
    stop("state annotation file must contain either an 'active' or 'category' column.")
  }

  hit <- match(node$mutation.report, anno$mutation.report)
  matched <- !is.na(hit)
  if (!any(matched)) {
    warning("No mutation.report values in state annotation matched selected states.")
    return(node)
  }

  if ("category" %in% names(anno)) {
    node$category[matched] <- as.integer(anno$category[hit[matched]])
    node$active[matched] <- node$category[matched] == 0L
  } else {
    active_value <- tolower(as.character(anno$active[hit[matched]]))
    node$active[matched] <- active_value %in% c("1", "true", "t", "yes", "y", "active")
    node$category[matched] <- ifelse(node$active[matched], 0L, 1L)
  }

  node
}

map_network_edges_to_nodes <- function(network_direction, node) {
  edges <- as.data.frame(network_direction)
  if (nrow(edges) == 0L) {
    return(data.frame(
      from = character(0),
      mutation.report.from = character(0),
      to = character(0),
      mutation.report.to = character(0),
      score = numeric(0),
      stringsAsFactors = FALSE
    ))
  }

  edges$mutation.report.from <- edges$from
  edges$mutation.report.to <- edges$to

  from_idx <- match(edges$mutation.report.from, node$mutation.report)
  to_idx <- match(edges$mutation.report.to, node$mutation.report)
  edges$from <- node$node[from_idx]
  edges$to <- node$node[to_idx]
  edges <- edges[!is.na(edges$from) & !is.na(edges$to), , drop = FALSE]

  if (!("score" %in% names(edges))) edges$score <- NA_real_
  edges[, c("from", "mutation.report.from", "to", "mutation.report.to", "score"), drop = FALSE]
}

plot_transition_network_pie <- function(node,
                                        edges,
                                        target,
                                        out_dir,
                                        early_label = "early",
                                        late_label = "late",
                                        label_size_threshold = 30,
                                        seed = 1) {
  if (!requireNamespace("igraph", quietly = TRUE)) {
    warning("Package 'igraph' is required to plot the transition network.")
    return(invisible(NULL))
  }

  vertices <- data.frame(name = node$node, stringsAsFactors = FALSE)
  edge_df <- edges[, c("from", "to"), drop = FALSE]
  g <- igraph::graph_from_data_frame(edge_df, directed = TRUE, vertices = vertices)

  set.seed(seed)
  layout <- igraph::layout_with_fr(g)

  total_n <- pmax(node$n, 1)
  max_n <- max(total_n, na.rm = TRUE)
  vertex_size <- 6 + 18 * sqrt(total_n / max_n)
  names(vertex_size) <- node$node

  pie_values <- lapply(seq_len(nrow(node)), function(i) {
    v <- c(node$n.early[[i]], node$n.late[[i]])
    if (sum(v) == 0) v <- c(1, 0)
    v
  })
  names(pie_values) <- node$node

  labels <- ifelse(node$n >= label_size_threshold, node$node.symbol, NA_character_)
  names(labels) <- node$node

  plot_one <- function() {
    old_mar <- par("mar")
    on.exit(par(mar = old_mar), add = TRUE)
    par(mar = c(0, 0, 1.5, 0))
    plot(
      g,
      layout = layout,
      vertex.shape = "pie",
      vertex.pie = pie_values[igraph::V(g)$name],
      vertex.pie.color = list(c("#F28E2B", "#4E79A7")),
      vertex.size = vertex_size[igraph::V(g)$name],
      vertex.label = labels[igraph::V(g)$name],
      vertex.label.cex = 0.55,
      vertex.label.color = "black",
      vertex.frame.color = ifelse(node$active[match(igraph::V(g)$name, node$node)], "#2F6B3F", "#555555"),
      edge.arrow.size = 0.25,
      edge.curved = 0.08,
      main = paste0(target, " mutation evolution network")
    )
    legend(
      "topleft",
      legend = c(early_label, late_label),
      fill = c("#F28E2B", "#4E79A7"),
      border = NA,
      bty = "n",
      cex = 0.8
    )
  }

  pdf(file.path(out_dir, paste0("transition_network_pie_", target, ".pdf")),
      width = 8, height = 8)
  plot_one()
  dev.off()

  tiff(file.path(out_dir, paste0("transition_network_pie_", target, ".tiff")),
       width = 8, height = 8, units = "in", res = 600)
  plot_one()
  dev.off()

  invisible(g)
}

build_P0 <- function(node, edges) {
  P0 <- diag(nrow(node))
  rownames(P0) <- colnames(P0) <- node$node

  if (nrow(edges) > 0L) {
    for (i in seq_len(nrow(edges))) {
      j <- match(edges$from[[i]], rownames(P0))
      k <- match(edges$to[[i]], colnames(P0))
      if (!is.na(j) && !is.na(k)) P0[j, k] <- 1
    }
  }

  P0
}

transitive_reachability <- function(P0) {
  reach <- P0 > 0
  n <- nrow(reach)
  for (k in seq_len(n)) {
    reach <- reach | (matrix(reach[, k], nrow = n, ncol = n) &
                        matrix(reach[k, ], nrow = n, ncol = n, byrow = TRUE))
  }
  dimnames(reach) <- dimnames(P0)
  reach
}

build_allowed_mask <- function(P0, category) {
  reach <- transitive_reachability(P0)
  P_mask <- matrix(0, nrow(P0), ncol(P0), dimnames = dimnames(P0))

  for (i in seq_len(nrow(P0))) {
    if (category[[i]] == 0L) {
      P_mask[i, reach[i, ]] <- 1
    } else {
      P_mask[i, i] <- 1
    }
  }

  P_mask
}

allowed_index <- function(P_mask) {
  do.call(rbind, lapply(seq_len(nrow(P_mask)), function(i) {
    cbind(row = i, col = which(P_mask[i, ] > 0))
  }))
}

matrix_to_vector <- function(P, P_mask) {
  idx <- allowed_index(P_mask)
  log(P[idx])
}

vector_to_matrix <- function(x, P_mask) {
  idx <- allowed_index(P_mask)
  P <- matrix(0, nrow(P_mask), ncol(P_mask), dimnames = dimnames(P_mask))
  P[idx] <- exp(x)
  P
}

initial_transition_guess <- function(P_mask, root_index) {
  P <- matrix(0, nrow(P_mask), ncol(P_mask), dimnames = dimnames(P_mask))
  for (i in seq_len(nrow(P_mask))) {
    allowed <- which(P_mask[i, ] > 0)
    P[i, allowed] <- 1 / length(allowed)
  }

  if (P[root_index, root_index] > 0) {
    P[root_index, root_index] <- 0.3
    P[root_index, ] <- P[root_index, ] / sum(P[root_index, ])
  }

  P
}

choose_root_index <- function(node, root_mutation_report = "") {
  idx <- which(node$mutation.report == root_mutation_report)
  if (length(idx) > 0L) return(idx[[1]])
  1L
}

estimate_transition_by_fsolve <- function(P_mask,
                                          p_early,
                                          p_late,
                                          root_index,
                                          maxiter = 200L,
                                          tol = .Machine$double.eps ^ 0.25) {
  if (!requireNamespace("pracma", quietly = TRUE)) {
    stop("Package 'pracma' is required for fsolve. Install it before running this step.")
  }

  r0 <- rep(0, nrow(P_mask))
  r0[root_index] <- 1
  x0 <- matrix_to_vector(initial_transition_guess(P_mask, root_index), P_mask)

  F <- function(x) {
    P <- vector_to_matrix(x, P_mask)

    pred_early <- 0.003333333 * t(r0) %*% matrix_power(P, 2) +
      0.649333333 * t(r0) %*% matrix_power(P, 3) +
      0.347333333 * t(r0) %*% matrix_power(P, 4)

    pred_late <- 0.022666667 * t(r0) %*% matrix_power(P, 8) +
      0.616333333 * t(r0) %*% matrix_power(P, 9) +
      0.359333333 * t(r0) %*% matrix_power(P, 10) +
      0.001666667 * t(r0) %*% matrix_power(P, 11)

    c(as.numeric(pred_early) - p_early,
      as.numeric(pred_late) - p_late,
      rowSums(P) - 1)
  }

  fit <- pracma::fsolve(F, x0, tol = tol, maxiter = maxiter)
  P <- row_normalize(vector_to_matrix(fit$x, P_mask))

  pred_early <- 0.003333333 * t(r0) %*% matrix_power(P, 2) +
    0.649333333 * t(r0) %*% matrix_power(P, 3) +
    0.347333333 * t(r0) %*% matrix_power(P, 4)

  pred_late <- 0.022666667 * t(r0) %*% matrix_power(P, 8) +
    0.616333333 * t(r0) %*% matrix_power(P, 9) +
    0.359333333 * t(r0) %*% matrix_power(P, 10) +
    0.001666667 * t(r0) %*% matrix_power(P, 11)

  list(
    P = P,
    fit = fit,
    fitted_early = as.numeric(pred_early),
    fitted_late = as.numeric(pred_late),
    residual_norm = sqrt(sum(F(fit$x) ^ 2))
  )
}

main <- function() {
  args <- parse_args(commandArgs(trailingOnly = TRUE))

  early_result <- arg_or(args$early_result, NA_character_)
  late_result <- arg_or(args$late_result, NA_character_)
  early_file <- arg_or(args$early_file, NA_character_)
  late_file <- arg_or(args$late_file, NA_character_)
  early_object <- arg_or(args$early_object, NA_character_)
  late_object <- arg_or(args$late_object, NA_character_)

  if ((is.na(early_result) && is.na(early_file)) ||
      (is.na(late_result) && is.na(late_file))) {
    stop(paste(
      "Usage:",
      "Rscript estimate_transition_P.R",
      "(--early_result <result_d5> or --early_file <cell.read.d5.RData>)",
      "(--late_result <result_d14> or --late_file <cell.read.d14.RData>)",
      "--target A21",
      sep = " "
    ))
  }

  target <- arg_or(args$target, "A21")
  guide_rna <- arg_or(args$guide_rna, if (target == "A21") {
    "GTTCCCGTCCAGTAATCGTG"
  } else {
    "GTCGTTGTAGCAACCTATCGGGTG"
  })

  selection <- arg_or(args$selection, "min_cells")
  allele_mode <- arg_or(args$allele_mode, "auto")
  min_cells <- as.integer(arg_or(args$min_cells, "10"))
  coverage <- as.numeric(arg_or(args$coverage, "0.90"))
  root_mutation_report <- arg_or(args$root_mutation_report, "")
  state_annotation <- arg_or(args$state_annotation, NA_character_)
  out_dir <- arg_or(args$output, file.path("result_transition_P", target))
  run_fsolve <- as_flag(args$run_fsolve, default = TRUE)
  maxiter <- as.integer(arg_or(args$maxiter, "200"))

  suppressPackageStartupMessages({
    library(dplyr)
    library(stringr)
  })
  source("utility_functions.R")

  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  early_cell <- load_cell_level_barcodes(
    result_dir = early_result,
    file = early_file,
    object = early_object,
    target = target
  )
  late_cell <- load_cell_level_barcodes(
    result_dir = late_result,
    file = late_file,
    object = late_object,
    target = target
  )

  if (identical(allele_mode, "auto")) {
    allele_mode_used <- if (identical(target, "A21") &&
                            all(c("mutation.correction1", "align.correction1",
                                  "mutation.report") %in% colnames(early_cell)) &&
                            all(c("mutation.correction1", "align.correction1",
                                  "mutation.report") %in% colnames(late_cell))) {
      "legacy_hgrna_A21"
    } else {
      "standard"
    }
  } else {
    allele_mode_used <- allele_mode
  }
  message("[", target, "] allele mode: ", allele_mode_used)

  early_node <- collapse_for_transition(
    early_cell,
    target = target,
    guide_rna = guide_rna,
    allele_mode = allele_mode_used
  )
  late_node <- collapse_for_transition(
    late_cell,
    target = target,
    guide_rna = guide_rna,
    allele_mode = allele_mode_used
  )
  message("[", target, "] early alleles: ", nrow(early_node),
          "; late alleles: ", nrow(late_node))

  node <- build_two_timepoint_node(
    early_node = early_node,
    late_node = late_node,
    min_cells = min_cells,
    selection = selection,
    coverage = coverage
  )
  if (nrow(node) == 0L) stop("No mutation states selected for target ", target)
  node <- apply_state_annotation(node, state_annotation)

  network_direction <- make.network.direction(node, guide_rna)
  edges <- map_network_edges_to_nodes(network_direction, node)

  P0 <- build_P0(node, edges)
  P_mask <- build_allowed_mask(P0, node$category)
  root_index <- choose_root_index(node, root_mutation_report)

  write.table(node, file.path(out_dir, paste0("transition_node_", target, ".tsv")),
              sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(edges, file.path(out_dir, paste0("transition_edges_", target, ".tsv")),
              sep = "\t", quote = FALSE, row.names = FALSE)
  plot_transition_network_pie(
    node = node,
    edges = edges,
    target = target,
    out_dir = out_dir,
    early_label = "d5",
    late_label = "d14"
  )

  message("[", target, "] states: ", nrow(node))
  message("[", target, "] direct edges in P0: ", sum(P0) - nrow(P0))
  message("[", target, "] active states: ", sum(node$active))
  message("[", target, "] allowed entries in P_mask: ", sum(P_mask))
  message("[", target, "] root state index: ", root_index)

  if (!run_fsolve) {
    write_matrix_tsv(P0, file.path(out_dir, paste0("P0_direct_adjacency_", target, ".tsv")))
    write_matrix_tsv(P_mask, file.path(out_dir, paste0("P_mask_allowed_", target, ".tsv")))
    saveRDS(
      list(node = node, edges = edges, P0 = P0, P_mask = P_mask, root_index = root_index),
      file.path(out_dir, paste0("transition_P_inputs_", target, ".rds"))
    )
    message("[", target, "] skipped fsolve; P0 and P_mask were written.")
    return(invisible(NULL))
  }

  result <- estimate_transition_by_fsolve(
    P_mask = P_mask,
    p_early = node$p.early,
    p_late = node$p.late,
    root_index = root_index,
    maxiter = maxiter
  )

  write_matrix_tsv(result$P, file.path(out_dir, paste0("P_transition_fsolve_", target, ".tsv")))
  write.table(
    data.frame(
      node = node$node,
      mutation.report = node$mutation.report,
      observed_early = node$p.early,
      fitted_early = result$fitted_early,
      observed_late = node$p.late,
      fitted_late = result$fitted_late,
      active = node$active
    ),
    file.path(out_dir, paste0("P_fsolve_fit_check_", target, ".tsv")),
    sep = "\t", quote = FALSE, row.names = FALSE
  )
  saveRDS(result, file.path(out_dir, paste0("P_transition_fsolve_", target, ".rds")))
  message("[", target, "] fsolve residual norm: ", result$residual_norm)
}

main()
